# Generated by Django 3.1 on 2020-10-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdid', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('descr1', models.TextField(max_length=100)),
                ('descr2', models.TextField(max_length=100)),
                ('detail', models.TextField()),
                ('remarks', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('Handlager', models.IntegerField()),
                ('lang_id', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ptype', models.CharField(max_length=10)),
                ('HarmonizedCode', models.IntegerField()),
                ('eccn', models.CharField(max_length=10)),
                ('lkz', models.CharField(max_length=2)),
                ('ag', models.CharField(max_length=1)),
                ('imageurl', models.CharField(blank=True, default='', max_length=100)),
                ('imagepath', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibaquotes.productstatus')),
            ],
        ),
    ]
