# Generated by Django 3.1.2 on 2020-10-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesagreement',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
