# Generated by Django 3.1 on 2020-10-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ptype',
            field=models.CharField(max_length=15),
        ),
    ]
