# Generated by Django 3.1 on 2020-10-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0002_auto_20201004_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.TextField(max_length=150),
        ),
    ]
