# Generated by Django 3.1.2 on 2020-10-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0002_auto_20201018_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=5)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=50)),
                ('request', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('executive', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('fax', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('exp_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='newsletter',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='quotesagreement',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='QuoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_num', models.IntegerField()),
                ('group_name', models.CharField(max_length=50)),
                ('item_num', models.IntegerField()),
                ('product_name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ibaquotes.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibaquotes.quote')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ibaquotes.client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ibaquotes.currency'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ibaquotes.paymentcondition'),
        ),
        migrations.AddField(
            model_name='quote',
            name='shipping_terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ibaquotes.shippingterm'),
        ),
    ]
