# Generated by Django 3.1.2 on 2020-10-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0003_auto_20201027_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
