# Generated by Django 3.1 on 2020-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0004_auto_20201005_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesAgreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('descr1', models.TextField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
