# Generated by Django 3.1.2 on 2020-10-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0004_auto_20201027_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='shipping_terms',
            new_name='shipping_term',
        ),
    ]
