# Generated by Django 3.1.2 on 2020-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0005_auto_20201029_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('executive', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('offer_alias', models.CharField(max_length=150)),
                ('offer_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='fax',
        ),
        migrations.AddField(
            model_name='quote',
            name='copy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='number',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=(1.5), max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotedetail',
            name='product_detail',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quotedetail',
            name='product_remarks',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
