# Generated by Django 3.1 on 2020-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0005_quotesagreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotesagreement',
            old_name='descr1',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quotesagreement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
