# Generated by Django 3.1.2 on 2020-11-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0006_auto_20201107_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdata',
            name='address',
            field=models.CharField(default='kendry@gmail.com', max_length=150),
            preserve_default=False,
        ),
    ]
