# Generated by Django 3.1 on 2020-10-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0006_auto_20201005_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'verbose_name': 'Product Status', 'verbose_name_plural': 'Product Status'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productstatus',
            table='product_status',
        ),
    ]
