# Generated by Django 3.1 on 2020-10-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0007_auto_20201005_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='quotesagreement',
            name='payment_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibaquotes.paymentcondition'),
        ),
        migrations.AddField(
            model_name='quotesagreement',
            name='shipping_terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibaquotes.shippingterm'),
        ),
    ]
