# Generated by Django 3.1 on 2020-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0008_auto_20201006_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesagreement',
            name='exp_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotesagreement',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
