# Generated by Django 3.1.2 on 2020-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0010_quotedetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedetail',
            name='group_tax',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='quotedetail',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='quotedetail',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
