# Generated by Django 3.1.2 on 2020-11-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0012_quotedetail_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
