# Generated by Django 3.1.2 on 2020-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0014_auto_20201109_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imageurl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagepath',
            field=models.ImageField(upload_to='products'),
        ),
    ]
