# Generated by Django 3.1.2 on 2020-11-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0016_auto_20201114_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='quoteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'QuoteStatus',
                'verbose_name_plural': 'QuoteStatus',
            },
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_condition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_term',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='ibaquotes.quotestatus'),
            preserve_default=False,
        ),
    ]
