# Generated by Django 3.1.2 on 2020-11-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0017_auto_20201115_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='payment_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ibaquotes.paymentcondition'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ibaquotes.shippingterm'),
        ),
    ]
