# Generated by Django 3.1.2 on 2020-11-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0019_configdata_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesagreement',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
