# Generated by Django 3.1.2 on 2020-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0023_auto_20201126_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harmonizedcode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
