# Generated by Django 3.1.2 on 2020-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0024_auto_20201126_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
