# Generated by Django 3.1.2 on 2020-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0025_auto_20201126_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='usergroup',
            field=models.IntegerField(blank=True),
        ),
    ]
