# Generated by Django 3.1.2 on 2020-11-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0026_auto_20201126_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='newsletter',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='usergroup',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
