# Generated by Django 3.1.2 on 2020-12-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0027_auto_20201126_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdata',
            name='company_img',
            field=models.ImageField(blank=True, null=True, upload_to='company'),
        ),
        migrations.AddField(
            model_name='configdata',
            name='pdf_observ_msg',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='configdata',
            name='pdf_top_msg',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
