# Generated by Django 3.1.2 on 2020-12-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0028_auto_20201208_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdata',
            name='pdf_observ_msg',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='configdata',
            name='pdf_top_msg',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
