# Generated by Django 3.1.2 on 2020-12-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0029_auto_20201208_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdata',
            name='pdf_img_msg',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
