# Generated by Django 3.1.2 on 2020-12-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0030_configdata_pdf_img_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='usergroup',
        ),
    ]
