# Generated by Django 3.1.2 on 2020-12-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0032_auto_20201213_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='payment_condition_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_condition_name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='shipping_term_name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_area',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
