# Generated by Django 3.1.2 on 2021-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibaquotes', '0034_auto_20210415_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configdata',
            options={'verbose_name': 'Config Data', 'verbose_name_plural': 'Config Data'},
        ),
        migrations.AlterField(
            model_name='quotedetail',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
